History
grey0ne/django-protector pull request #7
Opened 2019-05-20 12:05 UTC by vasili4396

2019-05-22 11:44 UTC, grey0ne commented on protector/querysets.py
> +    def __init__(self, model_queryset_name, **kwargs):
Тут имеет место излишняя абстракция. Лучше сделать два отдельных QuerySet, но более читаемых. Будем объективны - других типов связи здесь не появится.

2019-05-22 11:55 UTC, grey0ne requested changes

2019-05-22 11:55 UTC, grey0ne commented on protector/querysets.py
> +            GenericUserToGroup = apps.get_model('protector', 'GenericUserToGroup')
Тем более вот тут всплывает вполне себе не абстрактный GenericUserToGroup

2019-05-22 11:55 UTC, grey0ne commented on protector/models.py
> +        # As a drawback, we restrict creating in-memory objects that are already stored in db
А зачем мы это проверяем в init а не в save?

2019-05-22 11:55 UTC, grey0ne commented on protector/models.py
> +        return '{history_id} | initiated by {initiator} | {group_name} {group_id} for perm {permission}'.format(
тут не хватает change_type

2019-05-22 11:55 UTC, grey0ne commented on protector/models.py
> +        return '{history_id} | initiated by {initiator} | {group_name} {group_id}'.format(
и здесь change_type

2019-05-22 11:55 UTC, grey0ne commented on protector/models.py
> +    OWNER_VALUES_TO_SAVE_FOR_HISTORY,
Эти константы по идее будут не нужны, если не увлекаться излишней генерализацией

2019-05-22 11:55 UTC, grey0ne commented on protector/managers.py
> +            ownertopermission_generic_restriction_relations__owner_object_id__in=[self.instance.pk],
А почему здесь понадобилось это поменять?

2019-05-22 11:55 UTC, grey0ne commented on protector/managers.py
> +    def add(self, perm, reason, obj=None, responsible=None, roles=None, initiator=None):
initiator и responsible - одно и то же

2019-05-22 13:36 UTC, vasili4396 commented on protector/models.py
> +        # As a drawback, we restrict creating in-memory objects that are already stored in db
objects.create последовательно создает in-memory объект, и потом просто вызывает save.
в принципе можно было переопределить save, но тогда бы пришлось еще переопределять bulk_create, который save не делает. 
там еще осталась одна дыра с этой уникальностью через update. в принципе ее можно попробовать залатать, но там будут просто дико неэффективные костыли.

2019-05-22 13:37 UTC, vasili4396 commented on protector/managers.py
> +            ownertopermission_generic_restriction_relations__owner_object_id__in=[self.instance.pk],
потому что permission теперь находится в абстрактном классе, и у него
related_name='%(class)s_generic_restriction_relations'

2019-05-22 13:39 UTC, vasili4396 commented on protector/managers.py
> +    def add(self, perm, reason, obj=None, responsible=None, roles=None, initiator=None):
разве? а если будет скрипт это делать? ответственного можно поставить, а скрипт инициатором не сделаешь

2019-05-22 13:42 UTC, vasili4396 commented on protector/models.py
> +        return '{history_id} | initiated by {initiator} | {group_name} {group_id} for perm {permission}'.format(
добавил

2019-05-22 13:42 UTC, vasili4396 commented on protector/models.py
> +        return '{history_id} | initiated by {initiator} | {group_name} {group_id}'.format(
и сюда

2019-05-22 15:10 UTC, vasili4396 commented on protector/querysets.py
> +    def __init__(self, model_queryset_name, **kwargs):
разнес на 2  qs'a.

2019-05-22 15:16 UTC, vasili4396 commented on protector/querysets.py
> +            GenericUserToGroup = apps.get_model('protector', 'GenericUserToGroup')
Эта штука (то что пользователь является членом группы из самого себя) раньше в save'e была, пришлось ее оттуда убрать, потому что переопределился метод create и туда теперь reason и initiator передаются, которые конструктор GenericUserToGroup не знает.
В качестве drawback'a получаем, что эта проверка (пользователь сам в свою группу входит), происходит только в момент добавления нового perm'a пользователю, а не каждый раз, когда что-то сохраняем в базу (и в принципе пофиг, не очень-то часто что-то в базу сохраняем. в основном -- это операции удаления, создания, edit'a не очень много)

2019-05-22 15:17 UTC, vasili4396 commented on protector/models.py
> +    OWNER_VALUES_TO_SAVE_FOR_HISTORY,
я решил вынести в константы, чтобы убрать дублирование кода, потому что эти tuple'ы используются как в моделях, так и в queryset'ах.

2019-06-03 16:32 UTC, grey0ne commented on protector/managers.py
> +    def add(self, perm, reason, obj=None, responsible=None, roles=None, initiator=None):
Нет, это буквально одно и тоже, если неизвестен инициатор действия, то оба этих параметра пусты

2019-06-03 16:34 UTC, grey0ne commented on protector/models.py
> +        # As a drawback, we restrict creating in-memory objects that are already stored in db
Давай все же в save, это будет понятнее и код станет проще без необходимости разбора kwargs

2019-06-03 16:38 UTC, grey0ne commented on protector/querysets.py
> +            raise ValidationError(REASON_VALIDATION_ERROR)
Не понял зачем константа для текста эксепшена

2019-06-03 16:39 UTC, grey0ne commented on protector/querysets.py
> +        objs_to_delete = self.values(*GENERIC_GROUP_VALUES_TO_SAVE_FOR_HISTORY)
Можно достать список полей прямо из модели, отдельная константа не понадобится

2019-06-03 16:39 UTC, grey0ne commented on protector/querysets.py
> +            raise ValidationError(u'Point out the reason in case creation occurs')
А здесь оно строкой почему-то

2019-06-05 14:13 UTC, vasili4396 commented on protector/models.py
> +        # As a drawback, we restrict creating in-memory objects that are already stored in db
все же вынес в save

2019-06-05 14:13 UTC, vasili4396 commented on protector/querysets.py
> +        objs_to_delete = self.values(*GENERIC_GROUP_VALUES_TO_SAVE_FOR_HISTORY)
сделал так

2019-06-05 14:13 UTC, vasili4396 commented on protector/models.py
> +    OWNER_VALUES_TO_SAVE_FOR_HISTORY,
исправлено

2019-06-05 14:37 UTC, vasili4396 commented on protector/managers.py
> +    def add(self, perm, reason, obj=None, responsible=None, roles=None, initiator=None):
исправил

2019-06-07 12:15 UTC, grey0ne approved these changes

2019-06-07 12:17 UTC, merged